# Generated by Django 4.2.2 on 2023-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='film/img')),
                ('director', models.CharField(max_length=30)),
                ('writer', models.CharField(max_length=30)),
                ('Starring', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('running_time', models.CharField(max_length=20)),
            ],
        ),
    ]
